-- An SQL script that creates a stored procedure
-- that adds a new correction for a student
-- This procedure is taking in 3 inputs:
-- 'user_id': a users.id value
--      (you can assume user_id is linked to an existing users)
-- 'project_name': a new or already exists projects - if no
--      projects.name found in the table, you should create it
-- 'score': the score value for the correction
